name: tests

on:
  push:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version:
          - "3.12"
          - "3.13"
          - "3.14"
          - "3.15"
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v8.3.2
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
      - run: uv sync --locked --all-groups
      - run: uv run pytest
